apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: spring-mysql-demo
  description: Spring MySQL Demo
  tags:
    - app-accelerator
    - java
    - spring
    - web
    - tanzu
  annotations:
    'backstage.io/kubernetes-label-selector': 'app.kubernetes.io/part-of=spring-mysql-demo'
spec:
  type: service
  lifecycle: experimental
  owner: default-team
