apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: spring-mysql-demo
  labels:
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: demo-app
    tier: apptier
spec:
  params:
  - name: annotations
    value:
      autoscaling.knative.dev/minScale: "1"
  source:
    git:
      url: https://github.com/masanara/spring-mysql-demo
      ref:
        branch: main
