apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: mysql
  description: demo-db
  tags:
    - sql
  annotations:
    'backstage.io/kubernetes-label-selector': 'app=demo-app,tier=backenddb'
    'backstage.io/techdocs-ref': dir:.
spec:
  type: service
  lifecycle: production
  owner: default-team
  system: demo
  dependsOn:
    - resource:default/db-example
