apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: demo-app
  description: App Server
  tags:
    - java
  annotations:
    'backstage.io/kubernetes-label-selector': 'app=demo-app,tier=apptier'
    'backstage.io/techdocs-ref': dir:.
spec:
  type: service
  lifecycle: production
  owner: default-team
  system: demo
  dependsOn:
    - components:default/mysql
  providesApis:
    - user-api
